### ISSUE TITLE
modules moeten kunnen lanceren zonder te verbinden met port 5000

### ISSUE THREAD

**Issue by steviestickman** [R2D2-2019/r2d2-python-build#56]
de server module wil dat modules uitgevoerd kunnen worden, zelfs als ze niet kunnen connected met port 5000.

**Comment by florianhumblot** [comment]
Om de container te kunnen maken voor een module moet er een zogenaamde `image` gebouwd worden. 
Tijdens het bouwen van deze image worden de scripts uitgevoerd om op errors te checken, en de image build niet wanneer een van de stappen crasht.

Tijdens het builden kan een python-module geen verbinding maken met de master, aangezien het buildel volledig geisoleerd is, waardoor er een crash uit voorkomt en de build wordt gecanceled.

Een voorbeeld met de swarm_management module:

```python3

python3 main.py

Traceback (most recent call last):
  File "main.py", line 35, in <module>
    main()
  File "main.py", line 13, in main
    module = Module(Comm())
  File "/app/r2d2-python-build/client/comm.py", line 96, in __init__
    self.manager.connect()
  File "/usr/local/lib/python3.7/multiprocessing/managers.py", line 512, in connect
    conn = Client(self._address, authkey=self._authkey)
  File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 492, in Client
    c = SocketClient(address)
  File "/usr/local/lib/python3.7/multiprocessing/connection.py", line 619, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
The command '/bin/sh -c python3 main.py' returned a non-zero code: 1
```

Het is dus van belang dat modules *niet* crashen wanneer ze geen verbinding kunnen maken maar gewoon opnieuw proberen een verbinding aan te gaan.
